services:
  backup:
    image: atareao/volume-backup
    container_name: backup
    restart: always
    init: true
    environment:
      SCHEDULE: "0 3 * * *"
      MATRIX_HOST: "$MATRIX_HOST"
      MATRIX_TOKEN: "$MATRIX_TOKEN"
      MATRIX_ROOM: "$MATRIX_ROOM"
    volumes:
      - ./config.json:/config.json
      - ./config_ssh.txt:/config_ssh.txt
      - ./id_backupuser:/root/.ssh/id_backupuser
      - ./hooks:/hooks
      - atbackup:/backup
      - local_backup:/tmp/local_backup

volumes:
  atbackup: {}
  local_backup:
    external: true
